### ISSUE TITLE
Italics no longer works across multiple lines

### ISSUE THREAD

**Issue by alecjacobson** [fletcher/MultiMarkdown-5#10]
In multimarkdown 4.7.1, italics/emphasis would work even if the inner text spanned a newline character. For example:

    printf "_Multiline\nitalics_" | multimarkdown

produced

    <p><em>Multiline
    italics</em></p>

Now, in version 5.0.1 this is broken, so that 

    printf "_Multiline\nitalics_" | multimarkdown

produces

    <p>_Multiline
    italics_</p>

**Comment by alecjacobson** [comment]
Now I'm a little confused. On Mac OS X with MultiMarkdown 4.7.1 installed via homebrew, italics works across newline. But installing MultiMarkdown 4.7.1 on Linux Ubuntu, I get the same behavior as MultiMarkdown 5.0.1 (italics does not work across newline). Could this really be OS dependent?

**Comment by fletcher** [comment]
Not sure what you're doing in regards to 4.7.1, but I pushed a fix for 5 to the develop branch (will be included in next official release, or you can build now).

Thanks!
