### ISSUE TITLE
Build failures on current repository

### ISSUE THREAD

**Issue by numinasthmatic** [fletcher/MultiMarkdown-5#11]
Here's the output from my OS X Yosemite build, generated by following the README.md file.

he following tests FAILED:
	  1 - markdown-should-fail (Failed)
	  3 - mmd (Failed)
	  4 - latex (Failed)
	  7 - lyx (Failed)
	 10 - odf (Failed)
	 11 - critic-accept (Failed)
	 12 - critic-reject (Failed)
	 13 - critic-highlight (Failed)
Errors while running CTest
make: *** [test] Error 8

Is there anything obvious I should be looking for?

**Comment by fletcher** [comment]
ctest -V would give you more debugging info to see what's missing on your system.
