### ISSUE TITLE
Bug with newlines?

### ISSUE THREAD

**Issue by Skif-off** [fletcher/MultiMarkdown-5#14]
MultiMarkdown v.5.1.0 and _1.md_:
```
Installation
------------
Installing Geany is done by the following three commands:
$ ./configure
$ make
(as root)
% make install
```
Run ```multimarkdown.exe --batch --full 1.md``` and _1.html_ file contents:
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
</head>
<body>
<h2 id="installation">Installation</h2>

<p>Installing Geany is done by the following three commands:
$ ./configure
$ make
(as root)
% make install</p>

</body>
</html>
```
I tried CR, LF and CR+LF, but all text in one line ```<p></p>```. Is bug or I am doing something wrong?

**Comment by Skif-off** [comment]
I am stupid it seems: newline is ```\n\n```

**Comment by fletcher** [comment]
Nope.  Not a bug, just lack of understanding of Markdown syntax.  ;)

<https://daringfireball.net/projects/markdown/syntax>

Paragraphs are separated by '\n\n'.  A linebreak can be forced with '<space><space>\n'.

But what you're showing looks more like a code block and should be entered as such (either the standard Markdown indented code block, or a fenced MMD codeblock:  <http://fletcher.github.io/MultiMarkdown-5/fences.html>).

MMD also supports escaped newlines:  <http://fletcher.github.io/MultiMarkdown-5/escaped-newlines.html>
