### ISSUE TITLE
MMD and Homebrew problems

### ISSUE THREAD

**Issue by iandol** [fletcher/MultiMarkdown-5#17]
I'm certainly no Homebrew expert, nor Git expert, but I tried to update the homebrew formula to allow brew to update to the latest V5.2 (it is still stuck on v5.0), and I run into the following problem, using the V5.2.0 tag and revision hash:

```ruby
url "https://github.com/fletcher/MultiMarkdown-5.git", :tag => "v5.2.0", :revision => "101bbad1dc572c5d87788b2b17b6f9375f1d2bc8"
```

```
👉  brew install --build-from-source multimarkdown
==> Cloning https://github.com/fletcher/MultiMarkdown-5.git
Updating /Library/Caches/Homebrew/multimarkdown--git
fatal: Couldn't find remote ref refs/tags/v5.2.0
Error: Failed to download resource "multimarkdown"
Failure while executing: git fetch -q origin
```

Yet, using the V5.0 tag and revision:
```ruby
url "https://github.com/fletcher/MultiMarkdown-5.git", :tag => "v5.0", :revision => "47e7c4a2fac0271ee52ae0c7062a726978219341"
```

Homebrew builds it without issue. My naive assumption is that the V5.2.0 tag is not in the master branch, which is why it can't find it?

**Comment by iandol** [comment]
Ah, OK the tag is `:tag => "5.2.0"` even though previous tag was `:tag => "v5.0"`

**Comment by iandol** [comment]
Pull request here: https://github.com/Homebrew/homebrew/pull/50336

**Comment by fletcher** [comment]
Thanks for this!!
