### ISSUE TITLE
MMD 5.1 and 5.2 hang when parsing nested stong and emphasis

### ISSUE THREAD

**Issue by antons** [fletcher/MultiMarkdown-5#18]
First of all, thank you for you work on MultiMarkdown.

While testing MMD 5.1 and 5.2, we’ve discovered a serious performance regression from 5.0.1. It can be easily reproduced by parsing documents where the following example line is repeated more than once.

```
**b**, _u_, __v__, *__w__*, _**x**_, ***y***, ___z___, *t __w__ t*
```

- 5.0.1 has no probelms parsing documents no matter how many times the example line is repeated.
- 5.1 starts getting unacceptably slow around 5 or more lines. 
- 5.2 takes several seconds to parse 2 lines, and appears to never finish parsing documents which contain 3 or more lines.

**Comment by fletcher** [comment]
Yeah -- I alluded to this elsewhere when commenting about the 5.2 release and changes to strong/emph parsing.  I didn't have a good example that "broke" things though.  Just a general mild slowdown.

Using your example, I was able to experiment a bit and found a way to fix the problem.  Parsing 70 lines of your example is essentially "instantaneous".

Fix pushed to develop branch.

**Comment by antons** [comment]
Glad the test case was useful. Thank you!
