### ISSUE TITLE
Building multimarkdown-5 on Ubuntu 14.04 64bit

### ISSUE THREAD

**Issue by starlinq** [fletcher/MultiMarkdown-5#19]
Hi,

I am trying to build the multimarkdown following your instruction, however I got a problem
`
...
-- Build files have been written to: /home/vl/MultiMarkdown-5/build

~/MultiMarkdown-5$ make install
make: *** No rule to make target `install'.  Stop.
`

What is wrong? Should I change a current directory to "build" one before using install command?

Regards, VS

**Comment by fletcher** [comment]
Please read the 'README' file, specifically the "Compile from Source" section.  It has instructions on how to compile.

**Comment by starlinq** [comment]
Oops, I have overlooked the `cd build` before `make install`. Thanks.
