### ISSUE TITLE
Edge case placeholder

### ISSUE THREAD

**Issue by fletcher** [fletcher/MultiMarkdown-5#2]
(Leaving this here as a reminder to look into it at some point.)

The proper way of handling the following Markdown text is not clearly defined:

    *emph *with emph* in it*
    
    **strong **with strong** in it**

You can view some outputs from Babelmark 2:

<http://johnmacfarlane.net/babelmark2/?normalize=1&text=*emph+*with+emph*+in+it*%0A%0A**strong+**with+strong**+in+it**>

I have mixed feelings about how this should be handled -- It appears CommonMark is nesting tags within themselves.  This seems to generate valid HTML, since those tags can be nested.  It doesn't seem to break ODF.  However, it causes toggling `emph` on/off in LaTeX, but doesn't toggle `strong` there.

I'm inclined to leave things as is....

**Comment by ickc** [comment]
I clicked the link and seems like those who do the right things are

```
RDiscount 1.6.8
Python-Markdown 2.6.5
Parsedown 1.6.0
s9e\TextFormatter (Fatdown/PHP) 
Earmark 0.2.1
cebe/markdown 1.1.0
cebe/markdown MarkdownExtra 1.1.0
cebe/markdown GFM 1.1.0
```

I think it is how LaTeX behave too. It shows what the author means rather than what the syntax means.

By the way, just a question: why BabelMark doesn't include MultiMarkdown?

**Comment by fletcher** [comment]
I just pushed a commit to development branch that improves strong/emph parsing, and MMD does now allow nesting strong within strong, for example.  As noted above, however, the effect this has on the output is undefined and varies (HTML vs LaTeX vs ODF).  I don't recommend doing this, but it will be parsed appropriately.

**Comment by ickc** [comment]
I just wrote a expanded test of this kind yesterday, don't know if you are interested in it:

```
- 1 in 1: *some text *emphasized* again*

- 1 in 2: **some text *emphasized* again**

- 1 in 3: ***some text *emphasized* again***

- 2 in 1: *some text **emphasized** again*

- 2 in 2: **some text **emphasized** again**

- 2 in 3: ***some text **emphasized** again***

- 3 in 1: *some text ***emphasized*** again*

- 3 in 2: **some text ***emphasized*** again**

- 3 in 3: ***some text ***emphasized*** again***
```

And you can see the corresponding [Babelmark 2 - Compare markdown implementations](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+1+in+1%3A+*some+text+*emphasized*+again*%0A%0A-+1+in+2%3A+**some+text+*emphasized*+again**%0A%0A-+1+in+3%3A+***some+text+*emphasized*+again***%0A%0A-+2+in+1%3A+*some+text+**emphasized**+again*%0A%0A-+2+in+2%3A+**some+text+**emphasized**+again**%0A%0A-+2+in+3%3A+***some+text+**emphasized**+again***%0A%0A-+3+in+1%3A+*some+text+***emphasized***+again*%0A%0A-+3+in+2%3A+**some+text+***emphasized***+again**%0A%0A-+3+in+3%3A+***some+text+***emphasized***+again***%0A).

**Comment by fletcher** [comment]
I had already included that in the test suite, along with a few other scenarios including underscore versions of the above, and a couple of "intra-word" examples. 

<https://github.com/fletcher/MMD-Test-Suite/blob/master/MultiMarkdownTests/StrongAndEmph.text>

**Comment by ickc** [comment]
Hi,

I found that in the latest MMD (5.2.0), the following code will produce and unexpected result:

In MMD:

```latex
*text*, \\(a^* \equiv b^*\\)
```

After mmd2tex:

```latex
\emph{text\emph{, \textbackslash{}(a\^{}} \textbackslash{}equiv b\^{}}\textbackslash{})
```

which should be this instead:

```latex
\emph{text}, $a^* \equiv b^*$
```

I believe it is related to how nested emph is handled.

**Comment by fletcher** [comment]
Thanks -- you are correct.  I pushed a commit to the development branch that fixes this for Math, but the same problem exists for code spans and a few other structures.  I'm always worried that fixing this is going to slow down the parser.   I'll need to look at it and see if there is a better fix that keeps performance.
