### ISSUE TITLE
Math not rendering correctly in .html

### ISSUE THREAD

**Issue by va01** [fletcher/MultiMarkdown-5#24]
Hi I've recently installed MMD5 and want to use it in text that includes math. I'm using Fletcher's [documentation on math](http://fletcher.github.io/MultiMarkdown-5/math.html) but I'm not generating the same output. Here's what I'm doing:

**Input: .txt file**
```
Here’s some math:

$${x}_{1,2}=\frac{-b\pm \sqrt{{b}^{2}-4ac}}{2a}$$ 

end.
```

**Processing: Command-line code**

`multimarkdown file.txt > file.html`

**Output: Actual (.html)**
```
Here’s some math:

\[{x}_{1,2}=\frac{-b\pm \sqrt{{b}^{2}-4ac}}{2a}\]

end.

```
**Output: Desired (.html)**
The eqn. on [fletcher's page](http://fletcher.github.io/MultiMarkdown-5/math.html).

**Additional info.**
I installed on a Mac el capitan via the homebrew route on the [instructions page](http://fletcher.github.io/MultiMarkdown-5/installation.html).

**Comment by fletcher** [comment]
The actual output you describe appears correct (check the source of the page you reference to verify).

Did you properly set up the metadata, as described on that same page?

**Comment by va01** [comment]
Adding the metadata solved the problem. Thanks, Fletcher. My bad for not realizing the metadata was necessary for the desired output.
