### ISSUE TITLE
change of syntax compared with the Scrivener build-in version?

### ISSUE THREAD

**Issue by Fmajor** [fletcher/MultiMarkdown-5#3]
i started to use scrivener to do structure writing using "MMD to Latex" method, i have done some trials and found that there are some differences in the MMD syntax between the build-in multimarkdown compiler and the multimarkdown-5 installed from brew.

example:
using the build-in multimarkdown compiler, i got
     
    [#citekey]    => ~\citep{citekey}
    [#citekey;]  =>  \citet{citekey}
    [#Ferrarese&Merritt2000ApJ] => ~\citep{Ferrarese&Merritt2000ApJ}

"Ferrarese&Merritt2000ApJ" is a cite key defined in my .bib file

using the external multimarkdown-5(select the "Use XSLT post-processing" compile option in Scrivener), i got

     [#citekey]    => ~\citep{citekey}
     [#citekey;]  =>  ~\citep{citekey;}
     [#Ferrarese&Merritt2000ApJ] => error when compiling
        -:32: parser error : EntityRef: expecting ';'
        <p>Blabla, <span class="externalcitation">[#Ferrarese&Merritt2000ApJ, Gebhardt20
       
so are there some changes in syntax between the MMD5 and the build-in version in Scrivener?
And where can i get the full MMD2Latex transfer table for the latest version of MMD?

**Comment by fletcher** [comment]
I have no idea which version of MMD is being used in Scrivener. You'll have to talk to them about it.

The XSLT conversion of HTML to LaTeX is a *very* outdated approach (4-5 years or so???).    They're in the "MMD Support" package:

<https://github.com/fletcher/MMD-Support>

But again, I don't recommend using those, and they are no longer maintained.  The proper way to create LaTeX is simply to use MMD itself.  The only reason to use XSLT is you want to customize the way that LaTeX is created but don't want to modify the MMD code.

When compared to anything else, MMD-5 is "right", unless there's a bug.  ;)
