### ISSUE TITLE
add support for build over gcc on MSYS instead of MSVC

### ISSUE THREAD

**Issue by KammutierSpule** [fletcher/MultiMarkdown-5#35]
Note: I am not an expert.
I would like to build MMD on MSYS, it gives me trouble because MSVC is also installed.

I manually managed to cmake it by using:
$ cmake -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release ..

**Comment by fletcher** [comment]
I don't anticipate adding every conceivable build system to the project.  It starts to get really messy.  As you discovered, cmake is very flexible.  You're using the right approach.
