### ISSUE TITLE
printing / exporting pdf of images on fodt

### ISSUE THREAD

**Issue by KammutierSpule** [fletcher/MultiMarkdown-5#36]
Hi Fletcher,
I am trying the images feature. I can add it and see the images when I open it on Libreoffice, however, if I do a print preview or export to pdf they will now show.

I look on solution from web and looks everthing ok from Libreoffice side,
I try to hack the generated fodt and looks like it is related with using two frames / text box for displaying an image.

**Comment by KammutierSpule** [comment]
I found that this issue is due the:
"   <style:graphic-properties style:print-content=\"false\"
it will work if I change to:
"   <style:graphic-properties style:print-content=\"true\"

**Comment by fletcher** [comment]
Thanks for sending this.  I'll test it out and add to the next release.

**Comment by fletcher** [comment]
Fixed.  Thanks!
