### ISSUE TITLE
AttrKey AlphanumericAscii

### ISSUE THREAD

**Issue by KammutierSpule** [fletcher/MultiMarkdown-5#38]
Hi Fletcher,
Are there any reasons that AttrKey = < AlphanumericAscii+ >
does not allow other kind of characters? I was looking for ':' '_' '-' 

I thought it could be useful to add attributes on ODT that has this kind of format:
text:anchor-type

Do you think there are any issues with other syntax while adding this to the attribute keys?

**Comment by fletcher** [comment]
Attributes are used in HTML, LaTeX, and ODF.  At the time this feature was created acceptable characters were limited.  It may be possible to use a more expanded range of characters now, but I have not validated it across all use cases.

**Comment by KammutierSpule** [comment]
I implemented the capability to add (raw) attributes to fodt images (inline and block) on my branch:
https://github.com/KammutierSpule/MultiMarkdown-5/commit/c4942cffc5778c59e924132fb02ba21158c29cb1

**Comment by fletcher** [comment]
The attributes used in MMD are designed to be as generic as possible. I'm not sure this makes sense for the default behavior, but is obviously fine for you to use as you like on your own fork.
