### ISSUE TITLE
Documentation: Changed behavior with Markdown inside CriticMarkup 

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-5#45]
This snippet

```
{--Lorem *ipsum* **dolor** ***sit*** amet.--}

{++Lorem *ipsum* **dolor** ***sit*** amet.++}
```

was converted to:

``` html
<p><del>Lorem <em>ipsum</em> <strong>dolor</strong> <strong><em>sit</em></strong> amet.</del></p>

<p><ins>Lorem <em>ipsum</em> <strong>dolor</strong> <strong><em>sit</em></strong> amet.</ins></p>
```

with MultiMarkdown 4.5.2 using `-a -r` (I think this is the latest version which does it like this. With newer versions (also using `-a -r`) the output is:

``` html
<del>Lorem *ipsum* **dolor** ***sit*** amet.</del>

<ins>Lorem *ipsum* **dolor** ***sit*** amet.</ins>
```

I think it should be mentioned in the docs that in order to process Markdown inside CriticMarkup newer versions have to be used with `-a -r --process-html`.

The problem is, that with newer versions one can no longer choose to _not_ use `--process-html` without losing any Markdown processing inside CriticMarkup.

Or am I missing something?

**Comment by fletcher** [comment]
You're correct.  The `<del>`, `<ins>`, and `<mark>` tags were previously not being recognized as HTML.  By fixing this, it does cause the behavior you describe.

This is not entirely a bad thing, however, as it is really easy for CriticMarkup syntax to intersect with MMD markup in a way such that valid HTML is impossible to produce without a complicated algorithm to come up with a valid way of duplicating syntax.  This will allow a better job of ensuring valid HTML.
