### ISSUE TITLE
Cross-referencing with custom labels 

### ISSUE THREAD

**Issue by rodyo** [fletcher/MultiMarkdown-5#52]
Cross-referencing with custom section labels doesn't work when the section is embedded in a block-level HTML element. 

Code: 

    <div>
    # test [somelabel] #
    [this should be a ref to chapter test][somelabel].
    </div>

Output of `multimarkdown --to=html`:

    <div>                                                                                                                                 
    # test [somelabel] #
    [this should be a ref to chapter "test"][somelabel].
    </div>

Output of `multimarkdown --to=html --process-html`:

    <div>                                                                                                                                 
    <h1 id="somelabel">test</h1>
    <p>[this should be a ref to chapter test][somelabel].</p>
    </div>

However, using the auto-generated labels seems to work OK. Code: 

    <div>
    # test #
    [this should be a ref to chapter test][test].
    </div>

Output of `multimarkdown --to=html --process-html`:

    <div>                                                                                                                                 
    <h1 id="test">test</h1>
    <a href="#test">this should be a ref to chapter test</a>.
    </div>

The `{{TOC}}` feature also seems to be affected. 

Version: 

    $ multimarkdown --version`
    MultiMarkdown version 5.4.0

**Comment by fletcher** [comment]
MMD v 6 is now in alpha.  I won't be spending much time updating MMD 5 any more, as I my development time should be spent finishing (and then polishing) MMD 6.  

MMD 6 will handle HTML blocks in a different way, however.  It is based roughly on the way CommonMark handles HTML.  In short, by adding or removing whitespace between the HTML wrapping tag and the contents, you can change whether MultiMarkdown syntax is processed inside the tag.

<http://spec.commonmark.org/0.27/#html-blocks>

<https://github.com/fletcher/MultiMarkdown-6/>

**Comment by rodyo** [comment]
This is great news! I downloaded the MMD5 installer via your site, and thus missed that there is a newer version. I'll give that a try.
