### ISSUE TITLE
Installer error on win 10

### ISSUE THREAD

**Issue by Dan-Essin** [fletcher/MultiMarkdown-5#58]
C:\Program Files\MultiMarkdown 5.4.0

![2017-06-15_14-41-44](https://user-images.githubusercontent.com/1776053/27203136-485cc31a-51d9-11e7-9f00-e4eae9e3e04f.jpg)

**Comment by fletcher** [comment]
1.  I've never heard of this error.  Not to say that no one has experienced it, but it seems strange to just occur now.

2. MMD-5 is deprecated, so I recommend trying version 6.

3.  Either way, if you continue to have trouble with the installer you can use the portable version and install it manually wherever you like.
