### ISSUE TITLE
error with make -- ubuntu 16.04

### ISSUE THREAD

**Issue by prabhatkmishra** [fletcher/MultiMarkdown-5#59]
git log master..develop --format="*	%s" | sort | uniq > CHANGELOG-UNRELEASED
fatal: ambiguous argument 'master..develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
mkdir build 2>/dev/null
Makefile:91: recipe for target 'build' failed
make: [build] Error 1 (ignored)
cd build; rm -rf *
make -C submodules/greg
make[1]: Entering directory '/home/prabhat/Downloads/MultiMarkdown-5/submodules/greg'
cc -g -Wall -O3 -DNDEBUG    -c -o greg.o greg.c
cc -g -Wall -O3 -DNDEBUG    -c -o tree.o tree.c
cc -g -Wall -O3 -DNDEBUG    -c -o compile.o compile.c
cc -g -Wall -O3 -DNDEBUG  -o greg-new greg.o tree.o compile.o
mv greg-new greg
make[1]: Leaving directory '/home/prabhat/Downloads/MultiMarkdown-5/submodules/greg'
cd build; touch README.html; \
cmake -DCMAKE_BUILD_TYPE=Release ..
/bin/sh: 2: cmake: not found
Makefile:8: recipe for target 'release' failed
make: *** [release] Error 127

**Comment by fletcher** [comment]
MMD v5 is deprecated -- I recommend using v6.  I am not working on v5 any more.

Either way, v5 will build on Ubuntu if done correctly.  But v6 is better.

**Comment by prabhatkmishra** [comment]
Following error with version 6

git log master..develop --format="*    %s" | sort | uniq > CHANGELOG-UNRELEASED
fatal: ambiguous argument 'master..develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
mkdir build 2>/dev/null
Makefile:111: recipe for target 'build' failed
make: [build] Error 1 (ignored)
cd build; rm -rf *
cd build; \
cmake -DCMAKE_BUILD_TYPE=Release ..
/bin/sh: 2: cmake: not found
Makefile:9: recipe for target 'release' failed
make: *** [release] Error 127

**Comment by fletcher** [comment]
You do have `cmake` installed, right??
